### ISSUE TITLE
Combobox keyboard navigation does not follow currently selected item.

### ISSUE THREAD

**Issue by CasperH2O** [iNKORE-NET/UI.WPF.Modern#61] opened 2024-05-24 08:23 UTC
**Describe the bug**
As discussed with @bober95 and @Valkirie in #52. Made a new ticket as requested by @NotYoojun 

**To Reproduce**
1. Navigate a "long" dropdown which has more elements then can be shown on the screen right away using the keyboard, either with the tab key or up and down arrows.

**Expected behavior**
I'm honestly not sure what would be best or easiest, but perhaps simply keeping the current selection/focus in view and scrolling automatically?

**Screenshots**
[333068498-e5199f4a-35e5-4da6-9b33-07398a644246.webm](https://github.com/iNKORE-NET/UI.WPF.Modern/assets/14330834/7243c386-229e-4fb0-a291-571f269bda65)

**Desktop (please complete the following information):**
 - OS: Windows 10, Windows 11
- Version 10.0.19045 Build 19045

**Comment by Bober95** [comment] 2024-05-24 08:33
I will also add that the same problem occurs in DataGrid, ScrollViewerEx is also used there

**Comment by Bober95** [comment] 2024-07-03 23:07
Hi, I've been working on this problem for a while and I don't know exactly why it doesn't work, but removing this line solves the problem: `ScrollInfo = new ScrollInfoAdapter(ScrollInfo);` in file: ScrollViewerEx.cs

**Comment by CasperH2O** [comment] 2024-07-09 08:21
@NotYoojun thank you very much for the update and the new release (we updated right away, very exicted!).

In the release notes I read: 

> Disabled ForceUseSmoothScroll for ComboBox to fix the scrolling issues.

But could not pin point the commit that was relevant for this, can we consider this ticket closed/done now? 🙂

**Comment by NotYoojun** [comment] 2024-07-09 08:40
> @NotYoojun thank you very much for the update and the new release (we updated right away, very exicted!).
> 
> In the release notes I read:
> 
> > Disabled ForceUseSmoothScroll for ComboBox to fix the scrolling issues.
> 
> But could not pin point the commit that was relevant for this, can we consider this ticket closed/done now? 🙂

Hi there,
Is this problem fixed? If so, you can close this issue.
If something else happens, feel free to reopen.

**Comment by Bober95** [comment] 2024-07-09 08:54
The problem is not resolved, it still occurs. The full solution is in my previous comment

**Comment by Valkirie** [comment] 2024-07-09 08:57
> **[Bober95](/Bober95) ** commented

Any side effects ? If not, could you maybe produce a Pull Request ?

**Comment by NotYoojun** [comment] 2024-07-09 12:04
> > **[Bober95](/Bober95) ** commented
> 
> Any side effects ? If not, could you maybe produce a Pull Request ?

There might be. I guess virtualization features will no longer work. More tests needed.

**Comment by NotYoojun** [comment] 2024-08-29 09:05
Hey,

Pls check after the latest commit if the problem still exists.

**Closed** 2024-12-05 07:40 UTC
Labels: bug, help wanted
