### ISSUE TITLE
SettingCard and SettingsExpander

### ISSUE THREAD

**Issue by scx1125** [iNKORE-NET/UI.WPF.Modern#75] opened 2024-08-08 14:01 UTC
A great project that directly increases the life of WPF. I wonder if there are plans to add SettingCard and SettingsExpander components similar to winui3. Thank you very much.

**Comment by Aris-Offline** [comment] 2024-08-09 07:43
#69

**Comment by NotYoojun** [comment] 2024-08-09 08:09
Hello, it's the duplicate of #69. Since this issue is English and #69 is Chinese. I'm closing that one and go on this one.

**Comment by NotYoojun** [comment] 2024-08-09 08:10
@duduskz 请关注这里的进展

**Comment by NotYoojun** [comment] 2024-08-09 10:28
I've made the SettingsCard in my lastest commits, however:

Known issues that needs to be fixed:
- SettingsCard: nested ToggleSwitch wrong label direction
- SettingsCard: Responsive width layout
- SettingsCard: If clickable is true, the chevron size is incorrect

More things to do:
- SettingsExpander

**Comment by duduskz** [comment] 2024-08-09 13:41
wooow

**Comment by NotYoojun** [comment] 2024-08-10 05:02
Hey guys, please try the latest commit:
https://github.com/iNKORE-NET/UI.WPF.Modern/commit/11afaede2afa7aeac5f04d819024321fbb6949f7

@scx1125 @duduskz

**Comment by NotYoojun** [comment] 2024-08-18 16:14
Last but not least, the SettingExpanders now have incorrect style (look like expanders). After fixing this all settings controls are done.

**Comment by NotYoojun** [comment] 2024-10-25 09:04
Done!

**Closed by NotYoojun** 2024-10-25 09:04 UTC
Labels: enhancement

**Comment by NotYoojun** [comment] 2025-01-23 09:06
# 🎉 This issue has been fixed in iNKORE.UI.WPF.Modern 0.10.0!
More features and bug fixes available
Check out: https://github.com/iNKORE-NET/UI.WPF.Modern/releases/tag/v0.10.0
